### ISSUE TITLE
Rendering world by Noise script

### ISSUE THREAD

**Issue by GamePlayer-PL** [Broken-Lamp-A-Studio/PlatGen#4]
**Game version: 1.4.0** (unpublished/unfinished)

**Mainly suggestion: Rendering world by Noise**
 Ok, so first I maked something to generate cave structures in Scratch ( :p ): https://scratch.mit.edu/projects/441645873/
 But it's only image an caves. 

**implement the proposals:**
 I think about rendering world by layers:
  - Rendering ores etc (the easiler layer to make);
  - Rendering caves (here will be problem with writing size of caves);
  - Rendering structures (maybe the hardest thing);
  - Loading Story objects;

 But now the main problem is registering area as rendered. I want to make it without chunks so probably list/array will help with 
 register area. Also next problem (solved in scratch project) is render limit. Render is the thing, what will make playable (CPU will 
 not overheart).

**Comment by 6r1d** [comment]
Let's have my suggestion summarized, so it's always easy to return to. **Never render your world sequentially with a large cache.**
Since you know Minetest well, it has mapblocks it is rendering. And there is a map generator program that renders stuff based on preexisting conditions.
It allows to render the world on the fly, and if you remove a piece, re-rendered one will probably match.

To allow that, I proposed rendering based on formulas.
Use some formula that is repeatable enough. For example: `put dirt if x % 2 == 0`.
Your game world will have dirt done this way.

IIRC, I've recommended you the Simplex noise algorithm to show the speed. There are many [short ones](https://gist.github.com/patriciogonzalezvivo/670c22f3966e662d2f83) available.

With simplex noise dark spots might be caves and white ones might be air. Or vice versa. *You might want to add, multiply or change noise output to get more complex shapes and give player more space to move.* This will **solve** the "rendering caves** part for you.

Since you mention ores, it makes sense to use existing terrain (dark or white noise output spots) and add probability-based spots of ore.

I can't recommend anything about the structures yet.

**Comment by GamePlayer-PL** [comment]
> Never render your world sequentially with a large cache.

I will use area of active mapgen. But yes, I should do something with rendering it.


> To allow that, I proposed rendering based on formulas.
> Use some formula that is repeatable enough. For example: put dirt if x % 2 == 0.
Your game world will have dirt done this way.

You mean something like a world seed. I think, I can do that.

> With simplex noise dark spots might be caves and white ones might be air.

Yeah, also I think about air as block, to even register this point of map as rendered.

Generating caves will be started at 0,0 point, where player will spawn. But worse when player will built this place up, then player will be in blocks and that's bad.

**Comment by 6r1d** [comment]
> Generating caves will be started at 0,0 point, where player will spawn. But worse when player will built this place up, then player will be in blocks and that's bad.

I believe you can handle this easily. Pick a square like `64`×`64` nodes. When player is approaching its side, you generate one on the side and store somewhere. When player is far away, remove it from ram, but restore from disk when player returns.

> You mean something like a world seed. I think, I can do that.

I am not really sure about the terms there, but let's say a chest appears in the air when there's dirt under it. Some condition or conditions for each node.

**Comment by GamePlayer-PL** [comment]
Some progress: I maked chunk render, by 3 scripts. But loading/unloading chunks generating so much lags. So I don't connected Manu scene to Game scene. 

**Game scene**: res://scenes/GAME.tscn

**Comment by GamePlayer-PL** [comment]
and next progress: I optimalized rendering chunks, now working very well.

**Comment by GamePlayer-PL** [comment]
I published first version of rendering world. In future I will add saving world to file/files.

**Comment by GamePlayer-PL** [comment]
Script to saving world done. Rich rendering will be in next versions. Fast rendering working.
I'm closing this issue.
